name: window_manager_sub_window
description: This plugin allows Flutter desktop apps to resizing and repositioning the window.
version: 0.4.3
homepage: https://github.com/leanflutter/window_manager_sub_window

platforms:
  linux:
  macos:
  windows:

topics:
  - window
  - window-resize
  - window-manager
  - desktop
  - desktop-window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  screen_retriever: ^0.2.0

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowManagerSubWindowPlugin
      macos:
        pluginClass: WindowManagerSubWindowPlugin
      windows:
        pluginClass: WindowManagerSubWindowPlugin
