name: window_manager_sub_window_macos
description: macOS implementation of the window_manager_sub_window plugin.
version: 1.0.1
repository: https://github.com/leanflutter/window_manager_sub_window/tree/main/packages/window_manager_sub_window_macos

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowManagerSubWindowMacosPlugin
