name: window_manager_sub_window_platform_interface
description: A common platform interface for the window_manager_sub_window plugin.
version: 1.0.1
homepage: https://github.com/leanflutter/window_manager_sub_window/blob/main/packages/window_manager_sub_window_platform_interface

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2
